# Generated by Django 5.0.6 on 2025-11-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_is_featured_product_is_hot'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deal',
            field=models.BooleanField(default=False),
        ),
    ]
