# Generated by Django 6.0 on 2025-12-20 02:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('confirmed', 'Đã xác nhận'), ('processing', 'Đang xử lý'), ('shipped', 'Đang giao hàng'), ('delivered', 'Đã giao hàng'), ('cancelled', 'Đã hủy')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='store_order_status_7b2658_idx'),
        ),
    ]
